# Generated by Django 4.1.3 on 2023-01-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0005_alter_post_usu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usu',
        ),
    ]
